var fullName = 'Victor Kalinkin';
var isCool = true;
var totalPets = 0;
console.log('Full Name:', fullName);
console.log('Is cool?:', isCool);
console.log('Total Pets:', totalPets);
console.log('Type of fullName:', typeof fullName);
console.log('Type of isCool:', typeof isCool);
console.log('Type of totalPets:', typeof totalPets);
var unknown = null;
console.log('Unkown:', unknown);
console.log('Type of Unknown:', typeof unknown);
var never;
console.log('Never:', never);
console.log('Type of Never:', typeof never);
